POST http://localhost:8080/create HTTP/1.1
Content-Type: application/json

[
    {
        "name": "Do the dishes",
        "checked": false
    },
    {
        "name": "Go to grocerie store",
        "checked": false
    },
    {
        "name": "Take a shower",
        "checked": false
    }
]

###

PUT http://localhost:8080/update HTTP/1.1
Content-Type: application/json

[
    {
        "checked": true
    },
    {
        "name": "Take a shower"
    }
]

###

GET http://localhost:8080/list HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:8080/delete HTTP/1.1
Content-Type: application/json

{"checked": true}

###